name: Troc_graines_app

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/srv/backend
    working_dir: /srv/backend/troc_graines_backend
    ports:
      - "8000:8000"
    secrets:
      - db_url
    environment:
      DATABASE_URL_FILE: /run/secrets/db_url
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend/troc_graines_backend/public:/srv/backend/troc_graines_backend/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: local_db
    restart: always
    ports:
      - "5432:5432"
    secrets:
      - db_password
      - db_user
      - db_name
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    volumes:
      - ./backend/data:/var/lib/postgresql/data

  adminer:
    image: dockette/adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db

secrets:
  db_password:
    file: ./secrets/db_password.secret
  db_name:
    file: ./secrets/db_name.secret
  db_user:
    file: ./secrets/db_user.secret
  db_url:
    file: ./secrets/db_url.secret




